### ISSUE TITLE
Short description

### ISSUE THREAD

**Issue by JaimeRZP** [LSSTDESC/rail#134]
**Bug report: Golden Spike notebook link borken in ReadMe**

I don't know if this has been already reported (couldn't find an open issue with a quick search) but this link is broken:
See this line:
https://github.com/LSSTDESC/rail/blob/a403e62778d27ca3a86be1974af4dfe8b5668062/examples/goldenspike_examples/README.md?plain=1#L3C1-L3C157

**Comment by ztq1996** [comment]
Thank you for raising this. This is solved in PR #138 . Closing.
