### ISSUE TITLE
Quick start installation instructions

### ISSUE THREAD

**Issue by OliviaLynn** [LSSTDESC/rail#18]
On a call with @aimalz and @drewoldag, we observed that it would be nice to have a "quick start" section to the installation instructions for new users that want to hit the ground running.

Would also be a good exercise to make sure we _can_ even condense a minimal set of installation instructions (or if installation process is too complicated for this).

**Comment by olivialynn** [comment]
Documenting some trouble (plus solutions) I ran into when installing RAIL locally on a summer research student's laptop (an M1 Mac using Miniforge) -

**The steps that ultimately worked:**
```
conda create -y -n rail python=3.10 h5py healpy scikit-learn somoclu
conda activate rail
pip install pz-rail-hub
conda install numpy
conda install scipy
pip install astropy==5.3
```

**Reasons:**

- `conda install h5py` -> an issue with `tables`
- `conda install healpy` -> issue with healpy from pip
- `pip install cmake` -> arose from pip having trouble installing xgboost, but only needed to be run the one time
- `conda install numpy scipy` -> assuming pz-rail-hub messes with the dependencies grabbed from prev conda scikit-learn. I don't fully understand but this was necessary when double checking these install instructions on her machine
- `upgrade astropy from 5.1 to 5.3`	-> came from an issue running goldenspike: `concatenate() got an unexpected keyword arg ‘dtype’`

**Comment by eacharles** [comment]
Does this work:


mamba create -y -n rail python=3.10 h5py healpy scikit-learn somoclu numpy scipy astropy==5.3
conda activate rail
git clone <rail_hub>
cd rail_hub
pip install -e .

**Comment by eacharles** [comment]
I've added some instructions:

https://lsstdescrail.readthedocs.io/en/latest/source/installation.html

I'm going to close this for now, as we have a number of open tickets about improving the documentation.
