### ISSUE TITLE
Switch estimators over to parallelized versions

### ISSUE THREAD

**Issue by eacharles** [LSSTDESC/RAIL#184]
Now that @joselotl has added the stuff we need to qp and tables_io we should switch the estimators over being parallelized version.

This involves adding functionality to the estimator base class to handle the chunking, and then switching the sub-classes to work on chunks.

**Comment by aimalz** [comment]
Does this issue entail anything distinct from #138?

**Comment by eacharles** [comment]
This is a duplicate from #138
