### ISSUE TITLE
Outdated estimators explained in goldenspike

### ISSUE THREAD

**Issue by OliviaLynn** [LSSTDESC/rail#20]
The goldenspike.ipynb markdown cell called "Estimate photo-z posteriors" contains written descriptions of `randomPZ`, `trainZ`, and `BPZ_lite`, while the notebook's code has since been updated to use `BPZ_lite`, `KNearNeighPDF`, and `FZBoost`. 

These explanations should be updated to match.

There may be other discrepancies throughout the notebook--trying to wrap something up so I haven't checked.

**Comment by aimalz** [comment]
Sorry for missing this while I was out of commission last week, and thanks for taking care of it! I was working on #20 [in another branch](https://github.com/LSSTDESC/rail/tree/issue/20/update-golden-spike-descriptions) but let it succumb to scope creep so this is just to let people know that I'll continue working on that without reopening the original issue.
