### ISSUE TITLE
Some clean ups (tests, config files)

### ISSUE THREAD

**Issue by OliviaLynn** [LSSTDESC/rail#25]
I am cleaning up:

- RAIL/tests/creation - if we're organizing tests into subdirs, we should use more than one subdir. Electing to remove this.
- goldenspike configs - these are duplicated, and I kept them around for the time being, as I didn't want to accidentally remove the wrong one. Looking into which is the one in use (or if both are; in which case, pointing things to only use one)

Slightly longer term, and as a reminder to revisit, consider:

- Combining dsps code

**Comment by olivialynn** [comment]
closing as the remaining work is outlined in #15
