### ISSUE TITLE
Demos missing on readthedocs

### ISSUE THREAD

**Issue by aimalz** [LSSTDESC/rail#42]
I think some important things for notebook rendering got left out of the migration because the demos aren't on readthedocs at all anymore.

EDIT: @OliviaLynn has reminded me [it wasn't forgotten or anything](https://github.com/LSSTDESC/rail/commit/469f141a73ec6a4f5a500dc649a871544ce871e9), just postponed until after the migration due to speed of building the notebooks.

**Comment by eacharles** [comment]
I posted about this on slack.The notebook render times out on read the docs.So we will have to come up with some other strategy to auto render the notebooks.-eOn Jun 26, 2023, at 5:57 PM, Alex Malz ***@***.***> wrote:﻿
Assigned #42 to @eacharles.
