### ISSUE TITLE
Unexpected installation behavior of rail clone-source

### ISSUE THREAD

**Issue by olivialynn** [LSSTDESC/rail#45]
When I run the developer [installation instructions](https://lsstc.slack.com/archives/CQGKM0WKD/p1687886958588219) as written (running `rail clone-source --package-file rail_packages.yml` from within my top level rail directory), I end up with the rail ancillary packages (and rail_base!) as siblings to my rail directory. 

This adds unforeseen clutter to my development area, and renders paths illogical where the classic "everything goes into the same src/ directory" behavior is expected.

**Comment by eacharles** [comment]
Hmm.  This was the intended behavior.  It seemed natural to me to have them as siblings.-eOn Jun 27, 2023, at 7:36 PM, Olivia R. Lynn ***@***.***> wrote:﻿
When I run the developer installation instructions as written (running rail clone-source --package-file rail_packages.yml from within my top level rail directory), I end up with the rail ancillary packages (and rail_base!) as siblings to my rail directory.
This adds unforeseen clutter to my development area, and renders paths illogical where the classic "everything goes into the same src/ directory" behavior is expected.

**Comment by eacharles** [comment]
My intention was actually to have all the rail directories as siblings.    That just seems more logical to me, as they are all part of the same software release.On Jun 27, 2023, at 7:36 PM, Olivia R. Lynn ***@***.***> wrote:﻿
When I run the developer installation instructions as written (running rail clone-source --package-file rail_packages.yml from within my top level rail directory), I end up with the rail ancillary packages (and rail_base!) as siblings to my rail directory.
This adds unforeseen clutter to my development area, and renders paths illogical where the classic "everything goes into the same src/ directory" behavior is expected.
