### ISSUE TITLE
Clean up evaluation demo notebook and utils.py file.

### ISSUE THREAD

**Issue by eacharles** [LSSTDESC/rail#99]
rail/examples/evaluation_examples/utils.py -> This stuff is only used by the evaluation demo notebook. I think the answer here is to clean up that notebooks and either get stuff from somewhere else, or just add it to the notebook. If we have other notebooks that start needed some of this stuff, we can think about where it belongs in the wider RAIL ecosystem. This should be it's own issue.

**Comment by eacharles** [comment]
Though, if we refactor the Evaluation code, it might be better to wait...

**Comment by ztq1996** [comment]
Util refactoring is done in PR #138, closing issue.
